spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/thanthanwinn/config-server-microservices-.git"
          default-label: master
          searchPaths: config
          time-out: 5
          clone-on-start: true
          force-pull: true



          #search-locations: "file:///Users/ttw/blah/blah"
        #search-locations: classpath:/config
  profiles:
    active: git
  #active: native
  application:
    name: configserver
server:
  port: 8071
logging:
  level:
    org.springframework.cloud: DEBUG
