spring:
  cloud:
    config:
      server:
        native:
          git:
            uri:
            
          #search-locations: "file:///Users/ttw/blah/blah"
        #search-locations: classpath:/config
  profiles:
    active: git
  #active: native
  application:
    name: configserver
server:
  port: 8071
logging:
  level:
    org.springframework.cloud: DEBUG
